version: '3'

services:
  authority:
    build:
      context: ./authority
    restart: on-failure
    depends_on:
      - db
    networks:
      dns:
        ipv4_address: 172.19.0.2
    ports:
      - "8081:8081"

  edge:
    build:
      context: ./edge
    depends_on:
      - authority
    networks:
      dns:
        ipv4_address: 172.19.0.3

  cache:
    build:
      context: ./cache
    depends_on:
      - edge
    networks:
      dns:
        ipv4_address: 172.19.0.4
    ports:
      - "53:53"
      - "53:53/udp"

  db:
    build:
      context: ./db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: powerdns
      POSTGRES_PASSWORD: powerdns
      POSTGRES_DB: powerdns
    networks:
      dns:
        ipv4_address: 172.19.0.5
    ports:
      - "5432:5432"

networks:
  dns:
    ipam:
      config:
        - subnet: 172.19.0.0/24

volumes:
  db-data:
